FROM envoyproxy/envoy-dev:d00985acb839c00f4ac5d686061f10d3093c4a81

COPY ./envoy-proxy.yaml /etc/envoy-proxy.yaml
COPY ./grpc-server/gen/descriptors.pb /protos/descriptors.pb

RUN chmod go+r /etc/envoy-proxy.yaml

CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy-proxy.yaml", "--service-cluster", "backend-proxy"]
